---
- name: Ensure configuration fileas are up to date on target
  include_tasks: configure-files.yml
  with_list: "{{ svxlink_runner_config }}"
  loop_control:
    loop_var: fileinfo

- name: Make sure local-events.d directory exist
  file:
    path: "{{ svxlink_runner_config_dir + '/local-events.d' }}"
    owner: "{{ svxlink_runner_config_owner }}"
    group: "{{ svxlink_runner_config_group }}"
    #mode: 0775
    state: directory
  when: svxlink_runner_use_svxlink

- name: Symlink local-events.d directory
  file:
    path: "{{ svxlink_runner_eventsd_dir }}/local"
    src: "{{ (svxlink_runner_config_dir + '/local-events.d') | relpath(svxlink_runner_eventsd_dir) }}"
    #owner: root
    #group: root
    state: link
  when: svxlink_runner_use_svxlink

- name: Make sure local-sounds.d directory exist
  file:
    path: "{{ svxlink_runner_config_dir + '/local-sounds.d' }}"
    owner: "{{ svxlink_runner_config_owner }}"
    group: "{{ svxlink_runner_config_group }}"
    #mode: 0775
    state: directory
  when: svxlink_runner_use_svxlink

- name: Symlink local-sounds.d directory
  file:
    path: "{{ svxlink_runner_sounds_dir }}/local"
    src: "{{ (svxlink_runner_config_dir + '/local-sounds.d') | relpath(svxlink_runner_sounds_dir) }}"
    #owner: root
    #group: root
    state: link
  when: svxlink_runner_use_svxlink
