---
- name: Ensure configuration fileas are up to date on target
  include_tasks: configure-files.yml
  with_list: "{{ svxlink_runner_config }}"
  loop_control:
    loop_var: fileinfo

- name: Make sure local-events.d directory exist
  file:
    path: "{{ svxlink_runner_config_dir + '/local-events.d' }}"
    owner: "{{ svxlink_runner_config_owner }}"
    group: "{{ svxlink_runner_config_group }}"
    #mode: 0775
    state: directory
  when: svxlink_runner_use_svxlink

- name: Symlink local-events.d directory
  file:
    path: "{{ svxlink_runner_eventsd_dir }}/local"
    src: "{{ (svxlink_runner_config_dir + '/local-events.d') | relpath(svxlink_runner_eventsd_dir) }}"
    #owner: root
    #group: root
    state: link
  when: svxlink_runner_use_svxlink

- name: Make sure local-sounds.d directory exist
  file:
    path: "{{ svxlink_runner_config_dir + '/local-sounds.d' }}"
    owner: "{{ svxlink_runner_config_owner }}"
    group: "{{ svxlink_runner_config_group }}"
    #mode: 0775
    state: directory
  when: svxlink_runner_use_svxlink

- name: Symlink local-sounds.d directory
  file:
    path: "{{ svxlink_runner_sounds_dir }}/local"
    src: "{{ (svxlink_runner_config_dir + '/local-sounds.d') | relpath(svxlink_runner_sounds_dir) }}"
    #owner: root
    #group: root
    state: link
  when: svxlink_runner_use_svxlink

- name: Ensure that the PKI directory exist
  file:
    path: "{{ svxlink_runner_local_state_dir + item }}"
    owner: "{{ svxlink_builder_run_as_user }}"
    group: "{{ svxlink_builder_run_as_group }}"
    state: directory
  with_items:
    - '/'
    - '/pki'
  when: svxlink_runner_use_svxlink or svxlink_runner_use_svxreflector

- name: Ensure that the reflector PKI directories exist
  file:
    path: "{{ svxlink_runner_local_state_dir + item }}"
    owner: "{{ svxlink_builder_run_as_user }}"
    group: "{{ svxlink_builder_run_as_group }}"
    state: directory
  with_items:
    - '/pki/private'
    - '/pki/certs'
    - '/pki/pending_csrs'
    - '/pki/csrs'
  when: svxlink_runner_use_svxreflector

- name: Ensure that the reflector server root CA key is up to date
  copy:
    content: "{{ svxlink_runner_root_ca_key }}"
    dest: "{{ svxlink_runner_local_state_dir }}/pki/private/svxreflector_root_ca.key"
    owner: "{{ svxlink_builder_run_as_user }}"
    group: "{{ svxlink_builder_run_as_group }}"
    mode: 0620
  when: svxlink_runner_use_svxreflector and svxlink_runner_root_ca_key | length > 0

- name: Ensure that the reflector server root CA cert is up to date
  copy:
    content: "{{ svxlink_runner_root_ca_crt }}"
    dest: "{{ svxlink_runner_local_state_dir }}/pki/certs/svxreflector_root_ca.crt"
    owner: "{{ svxlink_builder_run_as_user }}"
    group: "{{ svxlink_builder_run_as_group }}"
    mode: 0664
  when: svxlink_runner_use_svxreflector and svxlink_runner_root_ca_crt | length > 0

- name: Ensure that the reflector CA bundle is up to date
  copy:
    content: "{{ svxlink_runner_root_ca_bundle }}"
    dest: "{{ svxlink_runner_local_state_dir }}/pki/ca-bundle.crt"
    owner: "{{ svxlink_builder_run_as_user }}"
    group: "{{ svxlink_builder_run_as_group }}"
    mode: 0664
  when: |
    (svxlink_runner_use_svxreflector or svxlink_runner_use_svxlink) and
    svxlink_runner_root_ca_bundle | length > 0
